/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { KeyValueDto } from './key-value-dto';


export interface BaseConfirmResponse { 
    details?: Array<KeyValueDto>;
    transactionToken?: string;
    transactionId?: string;
}

