/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TokenRequest { 
    browserAgent?: string;
    browserName?: string;
    browserVersion?: string;
    code?: string;
    clientDate?: string;
    clientGMT?: string;
    clientTime?: string;
    isMobileBrowser?: number;
    recordTime?: string;
    screenResolution?: string;
}

