/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TokenResponse { 
    token?: string;
    encryptionKey?: string;
    expiresIn?: number;
    beforeLoginTimeout?: number;
    expiresInWarning?: number;
    currentTime?: string;
    checkMsisdn?: boolean;
    timeout?: number;
    mainPageCacheTimeout?: number;
    isNotificationMenuVisible?: boolean;
    isQrMenuVisible?: boolean;
    cardImageCacheLastFlushDate?: string;
    isChatBotVisible?: boolean;
    backgroundImages?: string;
    currentBackgroundImage?: string;
    clientShowPageDefinitions?: string;
    activeVersions?: Array<number>;
    isLoadTestRefererShow?: boolean;
    sessionName?: string;
}

