import {
  formatFiles,
  generateFiles,
  Tree,
  names,
  offsetFromRoot,
} from '@nx/devkit';
import * as path from 'path';
import { libraryGenerator } from '@nx/angular/generators';

interface CreateFlowGeneratorOptions {
  name: string;
}

export async function createFlowGenerator(
  tree: Tree,
  options: CreateFlowGeneratorOptions
) {
  const name = names(options.name).fileName;
  const projectRoot = `libs/features/${name}`;
  
  await libraryGenerator(tree, {
    name: name,
    directory: `libs/features/${name}`,
    importPath: `@frontend/features/${name}`,
    standalone: true,
    skipModule: true,
    routing: true,
    lazy: true,
    unitTestRunner: 'vitest',
    linter: 'eslint',
    style: 'scss',
    skipFormat: true
  });

  // Delete default component generated by library generator
  tree.delete(`${projectRoot}/src/lib/${name}`);

  const templateOptions = {
    ...options,
    ...names(options.name),
    offsetFromRoot: offsetFromRoot(projectRoot),
    template: '',
  };

  generateFiles(
    tree,
    path.join(__dirname, 'files'),
    projectRoot,
    templateOptions
  );
  
  await formatFiles(tree);
}

export default createFlowGenerator;
